import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Bell, Bike } from 'lucide-react';
import { motion } from 'framer-motion';
import { useRiderStore } from '../../store/rider.store';
import { formatMoney } from '@grandxl/utils';
export function TopBar() {
    const { isOnline, rider, pendingJobs } = useRiderStore();
    const hasPendingJobs = pendingJobs.length > 0;
    const pendingKobo = rider?.earnings.pendingKobo ?? 0;
    return (_jsx("header", { className: "fixed left-0 right-0 top-0 z-40 border-b border-zinc-800/60 bg-zinc-950/95 backdrop-blur-md safe-top", children: _jsxs("div", { className: "flex items-center justify-between px-4 py-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "flex h-8 w-8 items-center justify-center rounded-xl bg-primary shadow-lg shadow-primary/20", children: _jsx(Bike, { size: 16, className: "text-white" }) }), _jsxs("div", { children: [_jsx("span", { className: "font-display text-sm font-bold tracking-tight text-zinc-100", children: "GrandXL" }), _jsx("span", { className: "ml-1.5 text-xs text-zinc-600", children: "Rider" })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [pendingKobo > 0 && (_jsx(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, className: "flex items-center gap-1 rounded-full bg-green-500/10 border border-green-500/20 px-2.5 py-1", children: _jsx("span", { className: "text-[10px] font-bold text-green-400 tabular-nums", children: formatMoney(pendingKobo, 'NGN') }) })), _jsxs("button", { className: "relative flex h-8 w-8 items-center justify-center rounded-xl transition-colors hover:bg-zinc-800 cursor-pointer", style: { touchAction: 'manipulation' }, "aria-label": "Notifications", children: [_jsx(Bell, { size: 17, className: hasPendingJobs ? 'text-amber-400' : 'text-zinc-500', strokeWidth: hasPendingJobs ? 2.5 : 1.75 }), hasPendingJobs && (_jsx(motion.span, { initial: { scale: 0 }, animate: { scale: 1 }, className: "absolute top-1 right-1 h-2 w-2 rounded-full bg-primary border border-zinc-950" }))] }), _jsxs("div", { className: `flex items-center gap-2 rounded-full px-3.5 py-1.5 text-xs font-semibold transition-all duration-300 ${isOnline ? 'bg-green-500/15 text-green-400 ring-1 ring-green-500/20' : 'bg-zinc-800 text-zinc-500'}`, children: [_jsx(motion.span, { className: `h-1.5 w-1.5 rounded-full ${isOnline ? 'bg-green-400' : 'bg-zinc-600'}`, animate: isOnline ? { scale: [1, 1.4, 1], opacity: [1, 0.5, 1] } : {}, transition: { duration: 1.5, repeat: Infinity } }), isOnline ? 'Online' : 'Offline'] })] })] }) }));
}
//# sourceMappingURL=TopBar.js.map